apiVersion: apps/v1
kind: Deployment
metadata:
  name: highchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highchat
  template:
    metadata:
      labels:
        app: highchat
    spec:
      containers:
      - name: highchat
        image: gcr.io/high-acfec/highchat-image:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: highchat-service
spec:
  selector:
    app: highchat
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
    nodePort: 30001
  selector:
    app: highchat
